- stoix/configs/default_ff_mdqn.yaml
- stoix/configs/system/ff_mdqn.yaml
- stoix/systems/q_learning/ff_mdqn.py
- stoix/utils/loss.py
> feat: add M-DQN

- stoix/configs/default_ff_qr_dqn.yaml
- stoix/configs/network/mlp_qr_dqn.yaml
- stoix/configs/system/ff_qr_dqn.yaml
- stoix/networks/heads.py
- stoix/systems/q_learning/ff_qr_dqn.py
- stoix/utils/loss.py
> feat: add qr-dqn

- requirements/requirements.txt
- stoix/configs/default_ff_ddqn.yaml
- stoix/configs/default_ff_dqn_reg.yaml
- stoix/configs/system/ff_dqn_reg.yaml
- stoix/systems/q_learning/ff_ddqn.py
- stoix/systems/q_learning/ff_dqn_reg.py
- stoix/utils/loss.py
Add DQN-reg and separate out ddqn and dqn
> feat: add DQN-reg and separate out ddqn and dqn

- stoix/configs/default_ff_dpo_continuous.yaml
- stoix/configs/system/ff_dpo.yaml
- stoix/systems/ppo/ff_dpo_continuous.py
- stoix/utils/loss.py
Add Discovered Policy Optimisation
> feat: add dpo

- requirements/requirements.txt
- stoix/configs/env/jaxmarl/mabrax.yaml
- stoix/configs/env/jaxmarl/mpe.yaml
- stoix/configs/env/jaxmarl/smax.yaml
- stoix/systems/ddpg/ff_d4pg.py
- stoix/systems/ddpg/ff_ddpg.py
- stoix/systems/ddpg/ff_td3.py
- stoix/systems/ppo/ff_dpo_continuous.py
- stoix/systems/ppo/ff_ppo.py
- stoix/systems/ppo/ff_ppo_continuous.py
- stoix/systems/ppo/rec_ppo.py
- stoix/systems/q_learning/ff_c51.py
- stoix/systems/q_learning/ff_qr_dqn.py
- stoix/systems/search/ff_az.py
- stoix/utils/logger.py
- stoix/utils/make_env.py
- stoix/wrappers/jaxmarl.py
- stoix/wrappers/truncation.py
Perform a variety of changes porting code from Mava.
> Fix jaxmarl wrapper

- README.md
- stoix/configs/default_ff_reinforce_continuous.yaml
- stoix/configs/system/ff_reinforce.yaml
- stoix/systems/vpg/ff_reinforce_continuous.py
Add REINFORCE with baseline for continuous environments
> feat: add continuous reinforce

- stoix/evaluator.py
> chore: remove commented code

- stoix/utils/logger.py
- stoix/wrappers/episode_metrics.py
> fix: issue with seed and episode metric calc

- stoix/systems/q_learning/ff_c51.py
- stoix/systems/q_learning/ff_ddqn.py
- stoix/systems/q_learning/ff_dqn.py
- stoix/systems/q_learning/ff_dqn_reg.py
- stoix/systems/q_learning/ff_mdqn.py
- stoix/systems/q_learning/ff_qr_dqn.py
Use the real next observation for q learning systems to allow truncated environments to work.
> fix: use the real final observation for transition

- stoix/configs/network/mlp_resnet.yaml
- stoix/configs/network/visual_resnet.yaml
- stoix/networks/resnet.py
Add resnet architecture for vector-based observations
> feat: add resnet for vector-based observations

- README.md
- stoix/configs/default_ff_dueling_dqn.yaml
- stoix/configs/network/mlp_dueling_dqn.yaml
- stoix/networks/dueling.py
- stoix/systems/q_learning/ff_dueling_dqn.py
Add dueling DQN.
For completeness sake.
> feat: add dueling dqn

- stoix/wrappers/brax.py
- stoix/wrappers/gymnax.py
- stoix/wrappers/xminigrid.py
> fix: add reward spec to wrappers

- stoix/utils/running_statistics.py
> feat: add running statistics utils modified from acme

- stoix/networks/distributions.py
- stoix/networks/heads.py
Add a Beta Distribution policy head
Some evidence suggests it is better
> feat: add beta distribution policy head

- stoix/configs/network/cnn.yaml
- stoix/configs/network/mlp.yaml
- stoix/configs/network/mlp_c51.yaml
- stoix/configs/network/mlp_d4pg.yaml
- stoix/configs/network/mlp_ddpg.yaml
- stoix/configs/network/mlp_dqn.yaml
- stoix/configs/network/mlp_dueling_dqn.yaml
- stoix/configs/network/mlp_mpo.yaml
- stoix/configs/network/mlp_mpo_continuous.yaml
- stoix/configs/network/mlp_qr_dqn.yaml
- stoix/configs/network/mlp_resnet.yaml
- stoix/configs/network/mlp_sac.yaml
- stoix/configs/network/muzero.yaml
- stoix/configs/network/rnn.yaml
- stoix/configs/network/sampled_muzero.yaml
- stoix/configs/network/visual_resnet.yaml
- stoix/configs/system/ff_d4pg.yaml
- stoix/configs/system/ff_ddpg.yaml
- stoix/configs/system/ff_td3.yaml
- stoix/systems/ddpg/ff_d4pg.py
- stoix/systems/ddpg/ff_ddpg.py
- stoix/systems/ddpg/ff_td3.py
> chore: slight change to configs

- requirements/requirements.txt
- stoix/systems/ddpg/ff_td3.py
- stoix/systems/sac/ff_sac.py
The double critic network was being initialised to the same network
> fix: double critic being initialised to same network

- plotting.ipynb
Add a plotting notebook.
Gives people an easy way to produce rliable plots using stoix json logs
> feat: add notebook to plot stoix algorithms

- requirements/requirements-dev.txt
- stoix/configs/network/cnn.yaml
- stoix/configs/network/cnn_noisy_dueling_c51.yaml
- stoix/configs/network/visual_resnet.yaml
- stoix/networks/torso.py
- stoix/utils/env_factory.py
- stoix/utils/logger.py
Add an MLP torso after the CNN layers in the CNN torso.
Easier to match existing architectures practically used in papers.
> feat: add MLP torso after CNN torso

- plotting/plotting.ipynb
- stoix/utils/logger.py
Add uuid to unique id
To ensure multi process runs dont write to same file.
> chore: add uuid to uniqueid

- stoix/systems/awr/ff_awr.py
- stoix/systems/awr/ff_awr_continuous.py
- stoix/systems/mpo/ff_mpo.py
- stoix/systems/mpo/ff_mpo_continuous.py
- stoix/systems/mpo/ff_vmpo.py
- stoix/systems/mpo/ff_vmpo_continuous.py
- stoix/systems/ppo/anakin/ff_dpo_continuous.py
- stoix/systems/ppo/anakin/ff_ppo.py
- stoix/systems/ppo/anakin/ff_ppo_continuous.py
- stoix/systems/ppo/anakin/ff_ppo_penalty.py
- stoix/systems/ppo/anakin/ff_ppo_penalty_continuous.py
- stoix/systems/ppo/anakin/rec_ppo.py
- stoix/systems/ppo/sebulba/ff_ppo.py
- stoix/tests/multistep_test.py
- stoix/utils/multistep.py
Fix issue with GAE calculation.
To ensure truncation is handled correctly.
Dont mask advantages.
Added test cases.
> fix: issue with GAE calc and add test case

- stoix/systems/awr/README.md
- stoix/systems/ddpg/README.md
- stoix/systems/impala/README.md
- stoix/systems/mpo/README.md
- stoix/systems/ppo/README.md
- stoix/systems/q_learning/README.md
- stoix/systems/sac/README.md
- stoix/systems/search/README.md
- stoix/systems/vpg/README.md
Add ReadMes for the algorithms
Its nice for people to be able to see the key papers in the folder itself.
> feat: add readme for algorithms

- stoix/systems/q_learning/ff_rainbow.py
- stoix/systems/q_learning/rec_r2d2.py
Change PER attribute
Flashbax API change
> fix: change fbx api

- .github/workflows/run_algs.yaml
- README.md
- bash_scripts/run-algorithms.sh
- stoix/configs/default/anakin/default_ff_spo.yaml
- stoix/configs/default/anakin/default_ff_spo_continuous.yaml
- stoix/configs/env/gymnax/breakout.yaml
- stoix/configs/logger/base_logger.yaml
- stoix/configs/network/mlp.yaml
- stoix/configs/system/spo/ff_spo.yaml
- stoix/configs/system/spo/ff_spo_continuous.yaml
- stoix/systems/spo/ff_spo.py
- stoix/systems/spo/ff_spo_continuous.py
- stoix/systems/spo/spo_types.py
- stoix/wrappers/brax.py
Add Continuous SPO
Thanks to @mvmacfarlane for the help and contributions.
> feat: add spo

- stoix/configs/network/specialised/kinetix_pixels.yaml
- Change the Kinetix pixels config to not have channels_first=True (which was wrong)
- Make the network smaller/more inline with the one used in the paper.
> Fix the Kinetix pixels config
